services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Subugoe\Find\:
    resource: '../Classes/*'

  Subugoe\Find\Service\ServiceProviderInterface:
    class: Subugoe\Find\Service\SolrServiceProvider
